#define LPAREN_TOK '('
#define RPAREN_TOK ')'
#define LCURLY_TOK '{'
#define RCURLY_TOK '}'
#define PLUS_TOK '+'
#define MINUS_TOK '-'
#define ASTERISK_TOK '*'
#define QUOTIENT_TOK '/'
#define MOD_TOK '%'
#define SEMICOLON_TOK ';'
#define ASSIGN_TOK '='
#define LT_TOK '<'
#define GT_TOK '>'
#define B_AND_TOK '&'
#define B_OR_TOK '|'
#define COMMA_TOK ','
#define NOT_TOK '!'

#define IDENTIFIER 256

#define IF_TOK 257
#define ELSE_TOK 258
#define FOR_TOK 259
#define WHILE_TOK 260
#define INT_TOK 261
#define AND_TOK 262
#define OR_TOK 263
#define EQ_TOK 264
#define DO_TOK 265
#define CHAR_TOK 266
#define FLOAT_TOK 267
#define RETURN_TOK 268
#define LT_EQ_TOK 269
#define GT_EQ_TOK 270
#define NOT_EQ_TOK 271
#define INC_TOK 272
#define DEC_TOK 273

#define INT_CONST_TOK 274
#define FLOAT_CONST_TOK 275